version: 2
updates:
  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /packages/cells
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /packages/core
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /packages/source
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /test-projects/cra5-gdg
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /test-projects/next-gdg
    schedule:
      interval: weekly
