# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Beta CI

on:
    push:
        tags:
            - "v*-*"

jobs:
    publish-core:
        defaults:
            run:
                working-directory: ./packages/core
        runs-on: ubuntu-latest
        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
              with:
                egress-policy: audit

            - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
            - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version: 20.10.0
            - name: Build
              run: npm install && npm run build
              working-directory: .
            - uses: JS-DevTools/npm-publish@0f451a94170d1699fd50710966d48fb26194d939 # v1.4.3
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  access: public
                  tag: beta
                  package: ./packages/core/package.json
    publish-cells:
        defaults:
            run:
                working-directory: ./packages/cells
        runs-on: ubuntu-latest
        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
              with:
                egress-policy: audit

            - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
            - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version: 20.10.0
            - name: Build
              run: npm install && npm run build
              working-directory: .
            - uses: JS-DevTools/npm-publish@0f451a94170d1699fd50710966d48fb26194d939 # v1.4.3
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  access: public
                  tag: beta
                  package: ./packages/cells/package.json
    publish-source:
        defaults:
            run:
                working-directory: ./packages/source
        runs-on: ubuntu-latest
        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
              with:
                egress-policy: audit

            - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
            - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version: 20.10.0
            - name: Bootstrap
              run: npm install && npm run build
              working-directory: .
            - uses: JS-DevTools/npm-publish@0f451a94170d1699fd50710966d48fb26194d939 # v1.4.3
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  access: public
                  tag: beta
                  package: ./packages/source/package.json
